#!/usr/bin/python3
#
# Copyright (c) 2020 Foundries.io
# SPDX-License-Identifier: Apache-2.0
#

import argparse
import logging
import json
import os

from apps.target_apps_store import ArchiveTargetAppsStore
from factory_client import FactoryClient


logger = logging.getLogger(__name__)


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('installed_versions')
    parser.add_argument('dst_dir')
    # TODO: remove it from here and meta-lmp
    parser.add_argument('arch')
    parser.add_argument('--images-root-dir', default=os.getenv('APP_IMAGE_DIR', '/var/cache/bitbake/app-images/'))
    return parser.parse_args()


def preload_app_images(target_json_file_filepath, dst_dir, app_images_root_dir):
    with open(target_json_file_filepath) as target_json_file:
        target_json = json.load(target_json_file)

    target_name = list(target_json.keys())[0]
    target = FactoryClient.Target(target_name, target_json[target_name])

    target_apps_store = ArchiveTargetAppsStore(app_images_root_dir)
    logging.info('Preloading app images for ' + target.name)
    _, app_image_tar, _ = target_apps_store.apps_location(target)

    if not target_apps_store.exist(target):
        logger.error('The app images are missing; container sha: {},'
                     ' location: {}'.format(target.sha, app_image_tar))
        exit(1)

    target_apps_store.copy(target, dst_dir)


if __name__ == '__main__':
    logging.basicConfig(level='INFO')
    fh = logging.FileHandler('/archive/preload-app-images.log')
    logging.getLogger(__name__).addHandler(fh)
    args = get_args()
    preload_app_images(args.installed_versions, args.dst_dir, args.images_root_dir)
